name: analytics_hub
description: Analytics hub for all providers.
version: 0.0.1
homepage: https://github.com/4akLoon/analytics_hub

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  logging: ">=1.0.0 <2.0.0"

dev_dependencies:
  test: ^1.24.0
  flutter_test:
    sdk: flutter
